title: Bhuvan Bharath blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://bhuvanbharath.github.io"
twitter_username: bhuvanbharatht
github_username:  bhuvanbharath

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
